Improved CPU timing performance of deepTauId v2
cms-tau-pog/cmssw pull request #126
Opened 2019-05-27 22:12 UTC by kandrosov

- Split network into 3 parts: inner, outer and core.
- Execute inner and outer sub-networks only for non-empty cells.

CPU usage test was performed by running `runDeepTauIDsOnMiniAOD.py` on 1000 ttbar events. Average time improved to about 0.06 s/event (to be compared to the previously measured rate of about 0.21 s/event).
http://kandroso.web.cern.ch/kandroso/cgi-bin/igprof-navigator/deepTau_2017v2p6_e6_split_cpu

@MRD2F, please, cross-check that the discriminators' outputs are not affected by this change.

2019-05-28 08:48 UTC, mbluj requested changes
@kandrosov thank you for the changes giving a speedup!

Questions: 
* Do I understand it correctly that the updated code requires three new traing files replacing the previous one? If so, please prepare also commit to Trainig-Files repo (if not done yet), please. I will test if all the stuff works withing MiniAOD sequence.
* Just to be sure: do the change maintain low memory usage?

A few occurrences of request to remove commented code inline.

I tend to merge the update when confirmed by @MRD2F that it reproduces results of previous implementation.

2019-05-28 08:48 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        // checkInputs(inputs, is_inner ? "egamma_inner_block" : "egamma_outer_block", dnn::NumberOfInputs, grid.nCellsEta,
Is there any important reason to keep this code commented out? If, so please comment on this in code otherwise remove.

2019-05-28 08:48 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        // checkInputs(inputs, is_inner ? "muon_inner_block" : "muon_outer_block", dnn::NumberOfInputs, grid.nCellsEta,
Is there any important reason to keep this code commented out? If, so please comment on this in code otherwise remove.

2019-05-28 08:48 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        // checkInputs(inputs, is_inner ? "hadron_inner_block" : "hadron_outer_block", dnn::NumberOfInputs, grid.nCellsEta,
Is there any important reason to keep this code commented out? If, so please comment on this in code otherwise remove.

2019-05-28 08:54 UTC, mbluj commented
@kandrosov please let to know RECO people (in PR to official CMSSW) that we are about to update DeepTau to this solution providing a speedup of  ~3.5 times.

2019-05-28 16:47 UTC, mbluj commented
Limited tests with 1k of SUSY bbH(125)->tau,tau events (~300 tau candidates passing new DMs & pT>18GeV) are successful: results got with updated code with splitting reproduce results got without the splitting. Please confirm this with higher statistic using mixture of taus and jet,e,mu->tau fakes. I think that reproduction of ROCs is not mandatory.
Please also remeasure CPU and memory usage.

2019-05-29 13:10 UTC, MRD2F commented
The new version doesn’t affects the discriminators output. This was tested for 4 samples: DY, tthad, H-tautau and QCD, with 10000 events. The plots with the difference of the output of this new version wrt the previous one can be found at the pdf I’m attaching.
[difference_in_versions_DeepTau.pdf](https://github.com/cms-tau-pog/cmssw/files/3232584/difference_in_versions_DeepTau.pdf)

The updated total memory consumption, calculated with 1000 events with a tthad sample is 21.53 MiB, this is calculated as the sum of the three bigger contributions:

1. DeepTauId::getPredictions =  15.88 MiB - that most part comes from pat::PackedCandidate::dzError(14.13 MiB) 
2. deep_tau::DeepTauBase::initializeGlobalCache = 3.96 MiB
3. DeepTauId::DeepTauId = 1.69 MiB
The file with all the information can be access at this link:  
http://mdidomen.web.cern.ch/mdidomen/cgi-bin/igprof-navigator/changes_PR_126/DeepTau_memory_usage/

The total CPU rates for each of the tested samples are (tested for 1000 events):

-TT :  0.11 s/evt. DeepTauId::getPredictions takes 0.08793 s/evt
(http://mdidomen.web.cern.ch/mdidomen/cgi-bin/igprof-navigator/changes_PR_126/DeepTauCPU_TT)

-H-tautau:  0.048 s/evt. DeepTauId::getPredictions takes 0.025 s/evt
(http://mdidomen.web.cern.ch/mdidomen/cgi-bin/igprof-navigator/changes_PR_126/DeepTauCPU_h-tautau)

-ttH: 0.14 s/evt. DeepTauId::getPredictions takes 0.11 s/evt
(http://mdidomen.web.cern.ch/mdidomen/cgi-bin/igprof-navigator/changes_PR_126/DeepTauCPU_ttH)

It was tested also the CPU timing and memory consumption for DeepTau inside the MinoAOD workflow. The memory consumption still is not ready, it takes a long time to run, so I’ll add the results in another comment. Both were also tested with the same tthad sample for 1000 events. The results for the timing was a rate of 1.06 s/evt, and the method  DeepTauId::getPredictions has a rate of 0.082 s/evt
(http://mdidomen.web.cern.ch/mdidomen/cgi-bin/igprof-navigator/changes_PR_126/DeepTau_MiniAOD)

2019-05-29 13:30 UTC, mbluj commented
@MRD2F, thank you. I see that memory usage is basically unchanged wrt non-split version, while CPU timing is reduced by a factor of 3-4. Physics performance stays unchanged.
=> merge.

2019-05-29 13:34 UTC, merged