Merge MVA DM
cms-tau-pog/cmssw pull request #138
Opened 2020-05-03 17:37 UTC by mhassans

I removed the model trained on 2016 (80X) sample, as suggested by Michal.

2020-06-18 16:52 UTC, mbluj requested changes
Dear Mohammad,
thank you for your development and sorry for belated review.

My main concern is presence of the new base class to produce MVADM discriminant called `MVADMDiscriminationProducerBase` - I think it is not needed as already existing `TauDiscriminationProducerBase` should provide what you need. Please check details in comment attached to header file of `MVADMDiscriminationProducerBase`.

Other general comment is about precision: you use double precision (double) for your computations (e.g. to get pi0 4-momentum), but it looks that final BDTs are in single precision (float). Also precision in miniAOD is usually single, so maybe it makes sense to use consistently single precision? It is not crucial comment but change will allow to save some resources, so generally good practice...

The rest comments (inline) is more or less pedantic comments on style. On top of those comments you might want to run `scram build code-format` and  `scram build code-checks` which will check against CMSSW code style rules and automatically apply them to your src.

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/interface/MVADMDiscriminationProducerBase.h
> +#ifndef RecoTauTag_RecoTau_MVADMDiscriminationProducerBase_H_
Is `MVADMDiscriminationProducerBase` needed? It looks that it should be enough to use already existing [`TauDiscriminationProducerBase`](https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_X/RecoTauTag/RecoTau/interface/TauDiscriminationProducerBase.h) (more precisely its pat::Tau based instance called `PATTauDiscriminationProducerBase`) as the base class for `PATTauDiscriminationMVADM.cc`. (I think you do not need your final derived class for reco::PFTaus, but in case derived class can be also templates with two specializations one for pat::Taus other for reco::PFTaus). Please follow is done in [PATTauDiscriminationAgainstElectronMVA6.cc](https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_X/RecoTauTag/RecoTau/plugins/PATTauDiscriminationAgainstElectronMVA6.cc) to declare many products (outputs of different raw IDs and the final MVADM classification)

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +            cms::Exception("MVA DM version not found") << "Requested version of ID does not exist.";
I propose to add explicitly a version requested to this exception printout to make it more verbose.

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +          version_ = iConfig.getParameter<std::string>("version");
Move initialization of `version_` to the initializer list of the class (after ":")

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +          reader_even_ = new TMVA::Reader();
Move initialization of MVA readers (from this and following lines) to the initializer list of the class (after ":")

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +          for(unsigned i=0; i<(unsigned)var_names_.size(); ++i){
`unsigned` -> `size_t` and remove cast, here and in following occurrences.

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    std::string version_ = "MVADM_2017_v1";
It can (and should) be const. It is not need to initialize it here as anyway it is set in c-tor.

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    TMVA::Reader *reader_even_;
The pointers to MVA readers can be probably const. as initialized once in c-tor and then only used for one object.

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    mutable std::vector<float> vars_ = std::vector<float>(24);
=> `mutable std::vector<float> vars_(24);` same in the following lines.

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    std::vector<TString> var_names_      = { "Egamma1_tau", "Egamma2_tau", "Epi_tau", "rho_dEta_tau", "rho_dphi_tau",
Can be const?

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    std::vector<TString> var_names_dm10_ = { "E1_overEa1", "E2_overEa1", "E1_overEtau", "E2_overEtau", "E3_overEtau",
Can be const?

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    typedef ROOT::Math::PtEtaPhiEVector Vector;
It is not fully intuitive to call 4-vetcor "Vector". Something like `PolarLorentzVector` or `PtEtaPhiELV` sound more intuitive. But note that in pat::PackedCandidate  `PolarLorentzVector` stands for `PtEtaPhiMVector`.

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +      if(decay_mode==0 || decay_mode==1) {
decay_mode==2 is ignored? It is very rare for HPS with dynamic strips, but exists.

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    Vector GetPi0 (std::vector<reco::CandidatePtr> gammas, bool leadEtaPhi) const {
Do not use capital letter for to start method name.

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +        double E = 0.;
`E` => `energy` to not use capital letter for variable name.

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +        pi0 = Vector(pt,eta,phi,E);
`pi0 = Vector(pt,eta,phi,E);` => `pi0.SetCoordinates(pt, eta, phi, E);`

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +        std::vector<reco::CandidatePtr> Associated = {};
decapitalize

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +            if(fabs(cands[i]->eta()-stripVector.eta())<etaAssociationDistance &&
fabs -> std::abs

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    std::pair<Vector,Vector> GetRho (const TauRef& tau, double gammas_pt_cut) const {
decapitalize name of the method.

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +        if(std::fabs(ROOT::Math::VectorUtil::DeltaR(s.first,tau->p4()))<cone_size) strips_incone.push_back(s);
std::fabs => std::abs here and in following

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +  std::pair<std::vector<Vector>, Vector> GetA1 (const TauRef& tau, float gammas_pt_cut) const {
decapitalize

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +        double mass = 0.1349;
pi and rho (L252) masses can be const members of the class (not need initialize them many times)

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +      double dM1 = std::fabs((hads[0]->p4()+hads[1]->p4()).M()-rho_mass);
std::fabs -> std::abs

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    for(auto s : strip_pairs) if(std::fabs(ROOT::Math::VectorUtil::DeltaR(s.first,tau->p4()))<cone_size) strips_incone.push_back(s);
std::abs

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    for (auto h : hads) prongs.push_back((Vector)h->p4());
Do you need this cast?

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +      a1_pi0_dEta = std::fabs(pi0.eta()-tau->eta());
std::fabs -> std::abs (here and following lines)

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
> +    availableDiscriminators+=["MVADM_2017_v1"]
Propose to put it explicitly to the list rather than extend it.

2020-06-18 16:52 UTC, mbluj commented on RecoTauTag/RecoTau/src/MVADMDiscriminationProducerBase.cc
> +#include "RecoTauTag/RecoTau/interface/MVADMDiscriminationProducerBase.h"
Please comment about need this base class attached to its header file.

2020-06-25 18:58 UTC, mhassans commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +        double E = 0.;
changed to tot_energy, so not to be confused with energy() function

2020-06-25 19:04 UTC, mhassans commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +        if(std::fabs(ROOT::Math::VectorUtil::DeltaR(s.first,tau->p4()))<cone_size) strips_incone.push_back(s);
Changed here, but I don't see any std::fabs immediately below this line. Do you mean everywhere in the code?

2020-06-26 14:32 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +        if(std::fabs(ROOT::Math::VectorUtil::DeltaR(s.first,tau->p4()))<cone_size) strips_incone.push_back(s);
Yes, I mean everywhere in the code.

2020-06-26 14:38 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    for (auto h : hads) prongs.push_back((Vector)h->p4());
I mean if you can use simply `h->p4()` instead of `(Vector)h->p4()`.

2020-09-03 15:36 UTC, mhassans commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +          version_ = iConfig.getParameter<std::string>("version");
Can you please elaborate more how exactly it can be initialized after ":"?

2020-09-03 15:40 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +            cms::Exception("MVA DM version not found") << "Requested version of ID does not exist.";
This is forgotten, please replace by something like this:
`cms::Exception("MVA DM version not found") << "Requested version of ID \""+version+"\"does not exist.";`

2020-09-03 15:46 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +          version_ = iConfig.getParameter<std::string>("version");
I mean add it to list of parameters initialised when the class is constructed:
 `: PATTauMVADMDiscriminationProducerBase(iConfig),` =>
`: PATTauMVADMDiscriminationProducerBase(iConfig),
   version_(iConfig.getParameter<std::string>("version")),`
and removal from body of the constructor.

2020-09-03 15:47 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    std::string version_ = "MVADM_2017_v1";
add constness (constexpr, I think)

2020-09-03 15:48 UTC, mhassans commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    for (auto h : hads) prongs.push_back((Vector)h->p4());
I think the cast is needed as the cast  converts "PtEtaPhiE4D"  to "Vector"(BTW,  I changed the name "Vector" to "PtEtaPhiEVector" in the latest version). I tried to remove cast but it complains.

2020-09-03 15:54 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +          reader_even_ = new TMVA::Reader();
as above, then I think can be made const.

2020-09-03 15:57 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +      if(decay_mode==0 || decay_mode==1) {
This was addressed, but as in other place decay_mode==2 was merged with 1 (which is more proper) it is not necessary here. So it is probably better to revert to the initial version:
`if(decay_mode==0 || decay_mode==1)`

2020-09-03 16:04 UTC, mhassans commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    std::string version_ = "MVADM_2017_v1";
I changed this line to `constexpr std::string version_;` and also moved the initialization of `version_` to the initialization list of the class. But now I receive this error `error: non-static data member 'version_' declared 'constexpr'`

2020-09-03 16:14 UTC, mbluj commented
Hi,
it looks that only a few small items should be addressed and then results with the final version compared against ones with the verion used in the CPH analysis before merging.
The last thing, after merge of the PR, it to prepare a recipe in the Tau POG TWiki.

2020-09-03 16:18 UTC, mbluj commented on RecoTauTag/RecoTau/plugins/PATTauDiscriminationMVADM.cc
> +    std::string version_ = "MVADM_2017_v1";
yes, shroud be `static constexpr`

2020-09-07 09:35 UTC, mbluj commented
+1

2020-09-07 09:37 UTC, mbluj approved these changes
All previously requested changes are implemented, @mhassans thank you.

2020-09-07 09:38 UTC, merged

2020-09-07 09:41 UTC, mbluj commented
This PR is merged, now please verify results with the updated code against original one (you can attach a few plots here) and then prepare a recipe for user at a Tau POG TWiki.

2020-09-07 09:44 UTC, mhassans commented
Thanks Michal for your helps in the process of merging. I contacted you via email about the comparison with HTT CP as well as the Twiki recipe. My main question is whether there is a convention to choose which variables (p_T, eta, etc.) and samples (H->tautau, Z->tautau) that I need to compare?

2020-09-15 15:08 UTC, mhassans commented
The attached file contains comparison between MVA DM merged in this PR and the one used in the Higgs CP analysis
[MVADM_compare.pdf](https://github.com/cms-tau-pog/cmssw/files/5225902/MVADM_compare.pdf)

2020-09-15 15:30 UTC, mbluj commented
Thanks!