Integration of DPFIsolation and DeepTauId
cms-tau-pog/cmssw pull request #98
Opened 2018-10-19 12:49 UTC by MRD2F

First implementation of DPFIsolation and DeepTauId integrated into cmssw.

2018-10-19 13:16 UTC, mbluj requested changes
Please provide a python configuration file in `RecoTauTag/RecoTau/test` to produce pat::Tau collection with the new Tau-Ids.  It can be called `runDeepTauIDsOnMiniAOD.py` or similar.

2018-10-19 13:16 UTC, mbluj commented on RecoTauTag/RecoTau/python/DPFIsolation_cff.py
> +from RecoTauTag.RecoTau.DPFIsolation_cff import *
Should be `DPFIsolation_cfi` rather than `cff`

2018-10-19 15:42 UTC, mbluj commented on RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
> +process = cms.Process('runDeepTauIDsOnMiniAOD')
Please use a shorter name of process, e.g. `TauID` or so.

2018-10-19 15:42 UTC, mbluj commented on RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
> +process.load('FWCore.MessageLogger.MessageLogger_cfi')
ll16-17: I propose to move customization of `MessageLogger` at the end of the file.

2018-10-19 15:42 UTC, mbluj commented on RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
> +process.MessageLogger.cerr.FwkReport.reportEvery = 100
I propose make frequency of report variable with number of events to be processed, e.g. like this
```
if process.maxEvents.input.value()>10:
     process.MessageLogger.cerr.FwkReport.reportEvery = process.maxEvents.input.value()//10
if process.maxEvents.input.value()>10000 or process.maxEvents.input.value()<0:
     process.MessageLogger.cerr.FwkReport.reportEvery = 1000
```

2018-10-19 15:42 UTC, mbluj commented on RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
> +options = VarParsing('analysis')
Is `VarParsing` intended to be used in any way in this example? If not, I would remove it - please comment.

2018-10-23 13:47 UTC, mbluj approved these changes

2018-10-23 13:56 UTC, merged

2018-10-23 14:00 UTC, mbluj commented
I find the code fine, so I merge it - thanks for your work. In addition I have had a set of small comments to the tauId embedding tool, i.e. `runTauIdMVA.py` and the test configuration `runDeepTauIDsOnMiniAOD.py`, but I found that it is simpler that I implement them myself. A pull request will be sent soon.

2018-10-23 14:18 UTC, mbluj commented
Hello again,
I have just merged to `cms-tau-pog:CMSSW_9_4_X_tau_pog_DNNTauID` updates mentioned above. 
I think you can start work on forward-porting DNN-related developments to 10_2_X and 10_4_X. I think that other release series are not important and can be ignored. I let you know names of branches to PR soon. 
Finally, when 10_4_X version is ready I will also ask for integration of training files.

2018-10-23 14:44 UTC, mbluj commented
Branches for 10_4_X and 10_2_X forwardports are respectively CMSSW_10_4_X_tau_pog_DNNTauIDs and CMSSW_10_2_X_tau_pog_DNNTauIDs

2018-10-23 15:52 UTC, MRD2F commented
> Branches for 10_4_X and 10_2_X forwardports are respectively CMSSW_10_4_X_tau_pog_DNNTauIDs and CMSSW_10_2_X_tau_pog_DNNTauIDs

Ok thanks for the information, I'll start to work on that

2018-10-24 15:39 UTC, kandrosov commented
@mbluj Looking through the code, I realized that current implementations of both DeepTauId and DPFIso are not threadsafe. Should this be fixed?

2018-10-24 15:51 UTC, mbluj commented
On Wed, Oct 24, 2018 at 5:44 PM Konstantin Androsov <
notifications@github.com> wrote:

> @mbluj <https://github.com/mbluj> Looking through the code, I realized
> that current implementations of both DeepTauId and DPFIso are not
> threadsafe. Should this be fixed?
>
I have not noticed this, and yes it should be fixed.

2018-10-24 16:00 UTC, veelken commented
Hi, 
I am wondering if we want to have the DeepTauId and DPFIso also for a dR=0.3 isolation cone - or is it better to commission the algorithm for dR=0.5 first and add a version for dR=0.3 later ?

2018-10-24 16:12 UTC, kandrosov commented
> Hi,
> I am wondering if we want to have the DeepTauId and DPFIso also for a dR=0.3 isolation cone - or is it better to commission the algorithm for dR=0.5 first and add a version for dR=0.3 later ?

Hello,
in my opinion, it is better to fully integrate the current implementations of the DNN discriminators first. Once it is done, it would be much easier to add dR=0.3 or new improved dR=0.5 versions.

2018-10-24 16:13 UTC, mbluj commented
Hi Christian,
I think it makes sense to test both deepTau and DPF as they are also with ttH->tau,tau signal and ttbar background. As far as I understand, both were trained with "dense" events in mind even if both of them use dR=0.5 rather than 0.3. Anyway, those discriminants are still experimental and feedback from ttH people is welcome. It is planned that they are provided for wider tests soon (say next week).

2018-10-24 16:14 UTC, kandrosov commented
> On Wed, Oct 24, 2018 at 5:44 PM Konstantin Androsov < ***@***.***> wrote: @mbluj <https://github.com/mbluj> Looking through the code, I realized that current implementations of both DeepTauId and DPFIso are not threadsafe. Should this be fixed?
> I have not noticed this, and yes it should be fixed.

Sorry, I have missed this problem as well... @MRD2F will create another PR that will address this issue.

2018-10-24 16:25 UTC, mbluj commented
On Wed, Oct 24, 2018 at 6:17 PM Konstantin Androsov <
notifications@github.com> wrote:

> On Wed, Oct 24, 2018 at 5:44 PM Konstantin Androsov < ***@***.***> wrote:
> @mbluj <https://github.com/mbluj> https://github.com/mbluj Looking
> through the code, I realized that current implementations of both DeepTauId
> and DPFIso are not threadsafe. Should this be fixed?
> I have not noticed this, and yes it should be fixed.
>
> Sorry, I have missed this problem as well... @MRD2F
> <https://github.com/MRD2F> will create another PR that will address this
> issue.
>
OK, thanks.